### ISSUE TITLE
Add Lokad

### ISSUE THREAD

**Issue by vermorel** [Kavignon/fsharp-companies#72]
Disclaimer: I am the CEO of Lokad.

While we also have C# and Typescript, we do have a large a growing F# codebase.

This link can be used for the source: https://www.lokad.com/software-engineering

Unfortunately, we do not support remote work at this point.

Ps: nice initiative!

**Comment by StachuDotNet** [comment]
@vermorel I'm sure @Kavignon would accept a relevant PR if you created one :)
